from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field

from app.models.interview_session import QuestionDifficulty, SessionStatus
from app.models.interview_turn import QuestionCategory


class AnswerEvaluationResult(BaseModel):
    """Multi-dimension answer evaluation conforming to Master Prompt Feature 8."""
    technical_accuracy: float = Field(ge=0.0, le=100.0, description="Accuracy of technical facts and principles")
    concept_understanding: float = Field(ge=0.0, le=100.0, description="Depth of foundational concept grasp")
    problem_solving: float = Field(ge=0.0, le=100.0, description="Methodology, trade-off analysis, edge cases")
    relevance: float = Field(ge=0.0, le=100.0, description="Direct alignment to question asked")
    completeness: float = Field(ge=0.0, le=100.0, description="Thoroughness covering key dimensions")
    communication: float = Field(ge=0.0, le=100.0, description="Articulation, pacing, conciseness")
    structure: float = Field(ge=0.0, le=100.0, description="Logical organization (e.g. STAR, architectural flow)")
    clarity: float = Field(ge=0.0, le=100.0, description="Precision of terminology and clarity")
    overall_score: float = Field(ge=0.0, le=100.0, description="Weighted composite score")
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    recommended_follow_up: str = ""


class InterviewPlanItem(BaseModel):
    """A planned interview curriculum node generated by LangGraph build_interview_plan."""
    topic: str
    category: str
    priority: int = 1
    rationale: str = ""
    target_difficulty: str = "medium"
    status: str = "pending"  # "pending", "in_progress", "completed", "skipped"


class TopicMasteryItem(BaseModel):
    """Tracks candidate mastery and attempts per competency."""
    topic: str
    score: float = 0.0
    turns_count: int = 0
    status: str = "untested"  # "untested", "struggling", "proficient", "mastered"


class FinalEvaluationSummary(BaseModel):
    """Holistic candidate evaluation computed at graph finalization."""
    overall_score: float = Field(ge=0.0, le=100.0)
    hiring_recommendation: str  # "Strong Hire", "Hire", "Lean Hire", "Lean No Hire", "No Hire"
    summary: str
    key_strengths: list[str] = Field(default_factory=list)
    growth_areas: list[str] = Field(default_factory=list)
    topic_scores: dict[str, float] = Field(default_factory=dict)
    total_turns: int = 0


class SessionCreateRequest(BaseModel):
    resume_id: UUID | None = None
    jd_id: UUID | None = None
    ats_analysis_id: UUID | None = None
    target_question_count: int = Field(default=5, ge=1, le=50)
    focus_categories: list[str] = Field(default_factory=list)
    starting_difficulty: QuestionDifficulty = QuestionDifficulty.medium
    adaptive_mode: bool = True


class SessionResponse(BaseModel):
    model_config = {"from_attributes": True}

    id: UUID
    user_id: UUID
    org_id: UUID | None = None
    status: SessionStatus
    current_difficulty: QuestionDifficulty
    current_topic: str | None = None
    current_question_index: int
    target_question_count: int
    langgraph_thread_id: str | None
    aggregate_score: float | None
    started_at: datetime | None
    completed_at: datetime | None = None
    created_at: datetime


class AnswerSubmitRequest(BaseModel):
    session_id: UUID
    turn_index: int
    audio_bytes_b64: str | None = None  # Base64-encoded WebM audio (optional if text provided)
    answer_text: str | None = None      # Direct text transcript (optional if audio provided)
    language: str = "en"


class TurnResponse(BaseModel):
    model_config = {"from_attributes": True}

    id: UUID
    session_id: UUID
    turn_index: int
    question_text: str
    question_category: QuestionCategory
    question_difficulty: str
    question_rationale: str | None = None
    raw_transcript: str | None = None
    audio_metrics: dict | None = None
    eval_scores: dict | None = None
    eval_feedback: str | None = None
    created_at: datetime


class NextQuestionResponse(BaseModel):
    question_text: str
    category: str
    difficulty: str
    rationale: str
    turn_index: int
    is_complete: bool
    evaluation: AnswerEvaluationResult | None = None
    topic_mastery: dict[str, TopicMasteryItem] | None = None
    final_summary: FinalEvaluationSummary | None = None


class SessionStateResponse(BaseModel):
    session_id: str
    status: str
    current_turn: int
    target_question_count: int
    current_difficulty: str
    current_topic: str | None = None
    interview_plan: list[InterviewPlanItem] = Field(default_factory=list)
    topic_mastery: dict[str, TopicMasteryItem] = Field(default_factory=dict)
    candidate_strengths: list[str] = Field(default_factory=list)
    candidate_weaknesses: list[str] = Field(default_factory=list)
    last_question: str | None = None
    last_evaluation: AnswerEvaluationResult | None = None
    all_turn_scores: list[float] = Field(default_factory=list)
    is_complete: bool = False
    final_summary: FinalEvaluationSummary | None = None


class WebSocketMessage(BaseModel):
    type: str  # "partial_transcript" | "question" | "error" | "complete"
    payload: dict
